/**
 *
 * Copyright (c) 2014, the Railo Company Ltd. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either 
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this library.  If not, see <http://www.gnu.org/licenses/>.
 * 
 **/
package lucee.runtime.db.driver;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import lucee.runtime.PageContext;

public interface StatementPro extends Statement {

	public boolean execute(PageContext pc, String sql) throws SQLException;

	public boolean execute(PageContext pc, String sql, int autoGeneratedKeys) throws SQLException;

	public boolean execute(PageContext pc, String sql, int[] columnIndexes) throws SQLException;

	public boolean execute(PageContext pc, String sql, String[] columnNames) throws SQLException;

	public ResultSet executeQuery(PageContext pc, String sql) throws SQLException;

	public int executeUpdate(PageContext pc, String sql) throws SQLException;

	public int executeUpdate(PageContext pc, String sql, int autoGeneratedKeys) throws SQLException;

	public int executeUpdate(PageContext pc, String sql, int[] columnIndexes) throws SQLException;

	public int executeUpdate(PageContext pc, String sql, String[] columnNames) throws SQLException;

}