<cfsetting showdebugoutput="false">
<cfinclude template="adminAIStore.cfm">
<cfif !structKeyExists(session, "password" & request.adminType)>
	<cfheader statuscode="403" statustext="Forbidden">
	<cfcontent reset="true" type="text/plain">Not authenticated<cfabort>
</cfif>
<cfif !AIHas("default:administrator")>
	<cfheader statuscode="503" statustext="Service Unavailable">
	<cfcontent reset="true" type="text/plain">No administrator AI connection configured<cfabort>
</cfif>
<cfparam name="form.sessionKey" default="">
<cfparam name="form.question" default="">
<cfparam name="form.formState" default="">
<cfparam name="form.flush" default="false">
<cfif !len(trim(form.sessionKey))>
	<cfheader statuscode="400" statustext="Bad Request">
	<cfcontent reset="true" type="text/plain">Missing sessionKey<cfabort>
</cfif>
<cfscript>
	pageHash = trim(form.sessionKey);
	pageStore = adminAIStoreGet(pageHash);

	if (form.flush) {
		systemMessage = structKeyExists(pageStore, "systemMessage") ? trim(pageStore.systemMessage) : "";
		if (!len(systemMessage)) {
			cfheader(statuscode=400, statustext="Bad Request");
			cfcontent(reset=true, type="text/plain");
			writeOutput("Unknown AI page session");
			cfabort();
		}

		ais = createAISession("default:administrator", systemMessage, 8, 0.3);
		stored = SerializeAISession(ais);
		label = "";

		try {
			meta = AIGetMetaData(ais);
			label = (meta.label ?: "") & " (" & (meta.model ?: "") & ")";
		}
		catch (any e) {
			label = "";
		}

		adminAIStoreSet(pageHash, {
			"serialized": stored,
			"label": label,
			"systemMessage": systemMessage
		});

		cfcontent(reset=true, type="application/json; charset=utf-8");
		writeOutput('{"ok":true}');
		cfabort();
	}

	if (!len(trim(form.question))) {
		cfheader(statuscode=400, statustext="Bad Request");
		cfcontent(reset=true, type="text/plain");
		writeOutput("Missing question");
		cfabort();
	}

	stored = structKeyExists(pageStore, "serialized") ? trim(pageStore.serialized ?: "") : "";
	systemMessage = structKeyExists(pageStore, "systemMessage") ? trim(pageStore.systemMessage ?: "") : "";

	if (!len(stored) || !len(systemMessage)) {
		cfheader(statuscode=400, statustext="Bad Request");
		cfcontent(reset=true, type="text/plain");
		writeOutput("Unknown AI page session");
		cfabort();
	}

	try {
		sessionLoad = adminAILoadSession(stored, systemMessage);
		ais = sessionLoad.ais;
		stored = sessionLoad.serialized;
	}
	catch (any e) {
		cfheader(statuscode=400, statustext="Bad Request");
		cfcontent(reset=true, type="text/plain");
		writeOutput("Invalid AI page session");
		cfabort();
	}

	label = structKeyExists(pageStore, "label") ? (pageStore.label ?: "") : "";
	userQuestion = trim(form.question);
	inquiryQuestion = userQuestion;
	if (len(trim(form.formState))) {
		inquiryQuestion &= adminAIFormStateMarker() & chr(10) & trim(form.formState);
	}
</cfscript>
<cfcontent reset="true" type="text/html; charset=utf-8">
<cfscript>
	answerBuffer = "";
	InquiryAISession(ais, inquiryQuestion, function(msg) {
		answerBuffer &= msg;
	});
	answerBuffer = adminAIFormatResponse(answerBuffer);
	writeOutput(answerBuffer);
	stored = SerializeAISession(ais);
	stored = adminAIHistorySetLastQuestion(stored, userQuestion);
	adminAIStoreSet(pageHash, {
		"serialized": stored,
		"label": label,
		"systemMessage": systemMessage
	});
	if (len(label)) {
		writeOutput("<h4>Generated by #encodeForHTML(label)#</h4>");
	}
</cfscript>
<cfabort>
