<cfscript>
	function adminAIStoreAppKey() {
		return "adminAIStore_" & hash((session.urlToken ?: "") & ":" & request.adminType, "SHA-256");
	}

	function adminAIStoreGetBucket() {
		var key = adminAIStoreAppKey();
		if (!structKeyExists(application, key) || !isStruct(application[key])) {
			application[key] = { "updated": now(), "pages": {} };
		}
		application[key].updated = now();
		return application[key];
	}

	function adminAIStoreCleanup() {
		for (var key in application) {
			if (left(key, 13) == "adminAIStore_" && isStruct(application[key])) {
				if (dateDiff("h", application[key].updated ?: now(), now()) > 24) {
					structDelete(application, key);
				}
			}
		}
	}

	function adminAIStoreGet(required string pageHash) {
		var bucket = adminAIStoreGetBucket();
		if (structKeyExists(bucket.pages, arguments.pageHash)) {
			return bucket.pages[arguments.pageHash];
		}
		return {};
	}

	function adminAIStoreSet(required string pageHash, required struct data) {
		var bucket = adminAIStoreGetBucket();
		bucket.pages[arguments.pageHash] = arguments.data;
		adminAIStoreCleanup();
	}

	function adminAIStoreDelete(required string pageHash) {
		var bucket = adminAIStoreGetBucket();
		structDelete(bucket.pages, arguments.pageHash);
	}

	function adminAILoadSession(required string stored, required string systemMessage) {
		var msg = trim(arguments.systemMessage);
		if (!len(msg)) {
			throw(message="Missing AI system message", type="admin.ai");
		}

		if (len(trim(arguments.stored))) {
			try {
				var data = deserializeJSON(arguments.stored);
				if (isStruct(data)) {
					data.systemMessage = msg;
					var ais = LoadAISession("default:administrator", data);
					return {
						"ais": ais,
						"serialized": SerializeAISession(ais)
					};
				}
			}
			catch (any e) {
			}
		}

		var aisNew = createAISession("default:administrator", msg, 8, 0.3);
		return {
			"ais": aisNew,
			"serialized": SerializeAISession(aisNew)
		};
	}

	function adminAISplitSusiActions(required string raw) {
		var result = {
			"displayHtml": arguments.raw,
			"actionsJson": ""
		};
		var match = reFind('(?i)<!--\s*susi-actions\s*-->\s*([\s\S]*?)\s*<!--\s*/susi-actions\s*-->', arguments.raw, 1, true);
		if (match.pos[1]) {
			result.actionsJson = trim(mid(arguments.raw, match.pos[2], match.len[2]));
			result.displayHtml = trim(
				left(arguments.raw, match.pos[1] - 1)
				& mid(arguments.raw, match.pos[1] + match.len[1])
			);
		}
		return result;
	}

	function adminAINeedsMarkdownConversion(required string text) {
		var t = trim(arguments.text);
		var hash = chr(35);
		if (!len(t)) {
			return false;
		}
		if (reFindNoCase("<h[1-6][^>]*>|<p[^>]*>|<ul[^>]*>|<ol[^>]*>|<li[^>]*>|<code[^>]*>", t)) {
			return false;
		}
		if (find(hash & hash & hash, t)) {
			return true;
		}
		if (reFind("\*\*[^*\r\n]+\*\*", t)) {
			return true;
		}
		if (reFind("(?m)^[\*\-]\s", t)) {
			return true;
		}
		return false;
	}

	function adminAIFormatResponse(required string raw) {
		var split = adminAISplitSusiActions(arguments.raw);
		var html = trim(reReplace(split.displayHtml, '(?i)<h4>\s*Generated by[\s\S]*?</h4>\s*$', '', 'one'));
		if (adminAINeedsMarkdownConversion(html)) {
			html = markdownToHTML(html);
		}
		if (len(split.actionsJson)) {
			html &= "<!-- susi-actions -->" & split.actionsJson & "<!-- /susi-actions -->";
		}
		return html;
	}

	function adminAIFormatAnswerForDisplay(required any answer) {
		if (isSimpleValue(arguments.answer)) {
			return adminAIFormatResponse(arguments.answer);
		}
		if (isArray(arguments.answer)) {
			var formatted = [];
			for (var part in arguments.answer) {
				if (isStruct(part) && (part.type ?: "") == "text" && structKeyExists(part, "content")) {
					var copy = duplicate(part);
					copy.content = adminAIFormatResponse(part.content);
					arrayAppend(formatted, copy);
				} else {
					arrayAppend(formatted, part);
				}
			}
			return formatted;
		}
		return arguments.answer;
	}

	function adminAIFormStateMarker() {
		return chr(10) & chr(10) & "Current form values (JSON):";
	}

	function adminAIStripFormStateFromQuestion(required string question) {
		var marker = adminAIFormStateMarker();
		var pos = findNoCase(marker, arguments.question);
		if (pos) {
			return trim(left(arguments.question, pos - 1));
		}
		return trim(arguments.question);
	}

	function adminAIFormatQuestionForDisplay(required any question) {
		if (isSimpleValue(arguments.question)) {
			return adminAIStripFormStateFromQuestion(arguments.question);
		}
		if (isArray(arguments.question)) {
			var formatted = [];
			for (var part in arguments.question) {
				if (isStruct(part) && (part.type ?: "") == "text" && structKeyExists(part, "content")) {
					var copy = duplicate(part);
					copy.content = adminAIStripFormStateFromQuestion(part.content);
					arrayAppend(formatted, copy);
				} else {
					arrayAppend(formatted, part);
				}
			}
			return formatted;
		}
		return arguments.question;
	}

	function adminAIHistorySetLastQuestion(required string stored, required string question) {
		try {
			var data = deserializeJSON(arguments.stored);
			if (structKeyExists(data, "history") && isArray(data.history) && arrayLen(data.history)) {
				data.history[arrayLen(data.history)].question = arguments.question;
				return serializeJSON(data);
			}
		}
		catch (any e) {
		}
		return arguments.stored;
	}
</cfscript>
