component {

	this.name	=	Hash( GetCurrentTemplatePath() ) & "2s";
	this.sessionManagement 	= false;

	this.datasource ={
	  		class: 'org.hsqldb.jdbcDriver'
			, bundleName: 'org.hsqldb.hsqldb'
			, bundleVersion: '2.3.2'
			, connectionString: 'jdbc:hsqldb:file:#getDirectoryFromPath(getCurrentTemplatePath())#/datasource/db'
		};

	// ORM settings
	this.ormEnabled = true;
	this.ormSettings = {
		// dialect = "MySQLwithInnoDB",
		// dialect = "MicrosoftSQLServer",
		dbcreate="dropcreate"
	};

	function onApplicationStart(){
		try{
			query {
			echo("DROP TABLE users");
			}
		}
		catch(local.e) {}

		query{
			echo("CREATE TABLE users( 
				id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
				DateJoined DATETIME )");
		}

	}

	function onRequestStart(){
		setting showdebugOutput=false;
	}
}