name: Build with Java 14

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
    - name: Run Lucee Build
      uses: ./.github/actions/main
      env:
        LUCEE_TEST_JAVA_HOME: ${ env.JAVA_HOME }
